<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>genertor</title>
</head>
<body>

</body>
</html>
<script>
    //1.基本
    /*function* helloWorldGenerator(){
        console.log('nihao')
        yield 'hello';
        //console.log('nihao')
        yield 'world';
        return 'ending';
    }
    var h = helloWorldGenerator();
    console.log(h.next());
    //console.log(h.next());*/


    //2.next中的参数
    /*function* f(){
        for(var i=0;true;i++){
            var rest = yield  i;
            console.log(rest)
            if(rest){
                i=-1;
            }
        }
    }
    var g =f();
    console.log(g.next());
    console.log(g.next());
    console.log(g.next(true));*/
    /*function* foo(x){
        var y = 2*(yield (x+1));
        var z = yield (y/3);
        return (x+y+z);
    }
    var a =foo(5);
    console.log(a.next())
    console.log(a.next(12))
    console.log(a.next(13))*/


    //3.for of
    /*function* foo(){
        yield 1;
        yield 2;
        yield 3;
        yield 4;
        yield 5;
        return 6;
    }
    for(let v of foo()){
        console.log(v);
    }
    console.log([...foo()]);
    console.log(Array.from(foo()))
    let [x,y,z,a,b]=foo();*/
    /*function* objectE(obj){
        let propKeys = Reflect.ownKeys(obj);
        for(let propKey of propKeys){
            yield [propKey,obj[propKey]];
        }
    }//为对象添加遍历接口
    let jane = {first:'jane',last:'dos'};
    for(let [key,value] of objectE(jane)){
        console.log(`${key}:${value}`);
    }*/


    //4.异常的抛出
    /*function* g(){
        //console.log('throwing an exception');
        yield 1;
        console.log('throwing an exception');
        throw new Error('generator break');
        yield 2;
        yield 3;
    }
    function log(generator){
        var v;
        console.log('starting generator');
        try{
            v= generator.next();
            console.log('第一次运行next方法:',v);
        }catch (err){
            console.log('捕捉错误',v)
        }
        try{
            v=generator.next();
            console.log('第二次运行next方法:',v)
        }catch (err){
            console.log('捕捉错误',v)
        }
        try{
            v=generator.next();
            console.log('第三次运行next方法:',v)
        }catch (err){
            console.log('捕捉错误',v)
        }
        console.log('caller done');
    }
    log(g());*/


    //5.generator return 给定返回值 并且终结generator函数遍历
    /*function* gen(){
        yield 1;
        yield 2;
        yield 3;
    }
    var g = gen();
    console.log(g.next());
    console.log(g.return("foo"));
    console.log(g.next());*/
    //如果generator函数中存在try finally return方法会在finally完成之后再执行
    /*function* numbers(){
        yield 1;
        try{
            yield 2;
            yield 3;
        }finally {
            yield 4;
            yield 5;
        }
        yield 6;
    }
    var num = numbers();
    console.log(num.next())
    console.log(num.next())
    console.log(num.return(7))
    console.log(num.next())
    console.log(num.next())*/


    //6.generator中的this
    /*function* g(){

    }
    g.prototype.hello = function(){
        return 'hi';
    }
    let obj = g();
    console.log(obj instanceof g)//true
    console.log(obj.hello())//hi
    /*function g(){

    }
    g.prototype.hello = function(){
        return 'hi';
    }
    let obj = g();
    console.log(obj instanceof g)//false
    console.log(obj.hello())//报错*/


    //7.状态机
    function* clock(_){
        while(true){
            yield  _;
            console.log('TIck');
            yield _;
            console.log('Tock');
        }
    }
    var a = clock();
    console.log(a.next())
    console.log(a.next())
    console.log(a.next())
    console.log(a.next())
    console.log(a.next())

</script>